version: '3'

services:
  ganache-cli:
    container_name: ganache-cli
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
    command: "--networkId 5777"
  
  monitor:
    build: ./tools/monitor
    environment:
      COIN_MARKET_CAP_API: ${COIN_MARKET_CAP_API:-}
    links:
      - ganache-cli
    restart: always

